site_draft:
  id: ehf-payment-g1-docs-processes-draft
  type: site
  path: target
  properties:
    domain: anskaffelser.dev
    path: payment/g1/docs/draft

site_current:
  mode: release
  id: ehf-payment-g1-docs-processes-current
  type: site
  path: target
  properties:
    domain: anskaffelser.dev
    path: payment/g1/docs/current